version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: location-service-api
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    networks:
      - location-network
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: location-service-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - location-network
    restart: unless-stopped

networks:
  location-network:
    driver: bridge

volumes:
  mongodb_data:
